-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE TEXTILE_SUSTAINABILITY;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.FACTORIES (
  FACTORY_ID VARCHAR(20) NOT NULL, FACTORY_NAME VARCHAR(200), PROVINCE VARCHAR(50), FACTORY_TYPE VARCHAR(30), CAPACITY FLOAT, EMPLOYEES INT, CERTIFICATION VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ORDERS (
  ORDER_ID VARCHAR(30) NOT NULL, STORE_ID VARCHAR(20), CUSTOMER_ID VARCHAR(20), ORDER_DATE TIMESTAMP, TOTAL_AMOUNT FLOAT, ITEMS INT, PAYMENT_METHOD VARCHAR(30), DELIVERY_TYPE VARCHAR(20), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTION_LOTS (
  RECORD_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), RECORD_DATE TIMESTAMP, VALUE FLOAT, CATEGORY VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.QUALITY_CHECKS (
  RECORD_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), RECORD_DATE TIMESTAMP, VALUE FLOAT, CATEGORY VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
