-- Generated from generator/demo_specs/aws-vietnam-textile-sustainability.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-textile-sustainability
-- This is the schema that is actually deployed for VIETNAM_TEXTILE_SUSTAINABILITY.

-- Alerts fire on the bottom tail of Recycled Content
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_RECYCLED_CONTENT) AS T
  FROM RAW.METRICS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_RECYCLED_CONTENT <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_RECYCLED_CONTENT), 2) AS AVG_RECYCLED_CONTENT,
  ROUND(AVG(f.KPI_CARBON_FOOTPRINT), 2) AS AVG_CARBON_FOOTPRINT,
  ROUND(AVG(f.KPI_CERTIFICATIONS), 2) AS AVG_CERTIFICATIONS,
  ROUND(AVG(f.KPI_ZERO_DISCHARGE), 2) AS AVG_ZERO_DISCHARGE,
  ROUND(AVG(f.KPI_SOLAR_COVERAGE), 2) AS AVG_SOLAR_COVERAGE,
  ROUND(AVG(f.KPI_WASTE_DIVERTED), 2) AS AVG_WASTE_DIVERTED
FROM RAW.METRICS f
JOIN RAW.DOCUMENTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_RECYCLED_CONTENT), 2) AS AVG_RECYCLED_CONTENT,
  ROUND(AVG(f.KPI_CARBON_FOOTPRINT), 2) AS AVG_CARBON_FOOTPRINT,
  ROUND(AVG(f.KPI_CERTIFICATIONS), 2) AS AVG_CERTIFICATIONS,
  ROUND(AVG(f.KPI_ZERO_DISCHARGE), 2) AS AVG_ZERO_DISCHARGE,
  ROUND(AVG(f.KPI_SOLAR_COVERAGE), 2) AS AVG_SOLAR_COVERAGE,
  ROUND(AVG(f.KPI_WASTE_DIVERTED), 2) AS AVG_WASTE_DIVERTED
FROM RAW.METRICS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_RECYCLED_CONTENT) AS KPI_RECYCLED_CONTENT, AVG(KPI_CARBON_FOOTPRINT) AS KPI_CARBON_FOOTPRINT, AVG(KPI_CERTIFICATIONS) AS KPI_CERTIFICATIONS, AVG(KPI_ZERO_DISCHARGE) AS KPI_ZERO_DISCHARGE, AVG(KPI_SOLAR_COVERAGE) AS KPI_SOLAR_COVERAGE, AVG(KPI_WASTE_DIVERTED) AS KPI_WASTE_DIVERTED FROM RAW.METRICS),
     en AS (SELECT SUM(KPI_WATER_USAGE_MTD) AS KPI_WATER_USAGE_MTD FROM RAW.DOCUMENTS)
  SELECT 1 AS SORT_ORDER, 'Recycled Content' AS TITLE, KPI_RECYCLED_CONTENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RECYCLED_CONTENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Water Usage (MTD)' AS TITLE, KPI_WATER_USAGE_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_WATER_USAGE_MTD) / 1000)) AS DECIMAL(38,0))) || 'K' || ' ' || 'm³' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Carbon Footprint' AS TITLE, KPI_CARBON_FOOTPRINT AS VALUE_NUM, '-' || TO_VARCHAR(CAST(ROUND((KPI_CARBON_FOOTPRINT)) AS DECIMAL(38,0))) || '% YoY' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Certifications' AS TITLE, KPI_CERTIFICATIONS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CERTIFICATIONS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Zero Discharge' AS TITLE, KPI_ZERO_DISCHARGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ZERO_DISCHARGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Solar Coverage' AS TITLE, KPI_SOLAR_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SOLAR_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Waste Diverted' AS TITLE, KPI_WASTE_DIVERTED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_WASTE_DIVERTED)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
