-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Sustainability Compliance
-- ============================================================================
USE DATABASE TEXTILE_SUSTAINABILITY;
USE SCHEMA ML;

-- ML.FORECAST: TEXTILE_SUSTAINABILITY_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.TEXTILE_SUSTAINABILITY_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FORECAST_INPUT'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.TEXTILE_SUSTAINABILITY_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.TEXTILE_SUSTAINABILITY_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: TEXTILE_SUSTAINABILITY_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.TEXTILE_SUSTAINABILITY_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.TEXTILE_SUSTAINABILITY_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.TEXTILE_SUSTAINABILITY_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'), SERIES_COLNAME => 'ENTITY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

